import styled from '@emotion/styled'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import UAFlag from '../public/assets/images/flag-ukraine.png'

const Container = styled.main`
  display: flex;
  justify-content: center;

  align-items: center;
    height: 100vh;
    width: 100vw;
    justify-content: center;
    align-content: center;
    flex-wrap: nowrap;
    flex-direction: row;
    gap: 15px;

  h1 {
    font-size: 60px;
    font-weight: bold;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  section {
        display: flex;
    flex-direction: column;
    align-content: center;
    justify-content: center;
    align-items: center;

  }

`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1>
          Show some ❤️ for 
        </h1>
        <Image src={UAFlag} alt="Ukraine flag" height={100} width={100} placeholder="blur" />
        
      </section>
    </Container>
  )
}

export default Home
